import type { Metadata } from "next";
import "../../styles/globals.css";
import { Icons } from "@/components/Icons";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import i18nConfig from "@/app/i18nConfig";
import initTranslations from "@/app/i18n";
import TranslationProvider from "@/app/[locale]/TranslationProvider";
import { StoreProvider } from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "Lasertag",
  description: "Generated by create next app",
};

const i18nNamespaces = ["translation"];

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <StoreProvider>
      <html lang={locale}>
        <body className="font-manrope">
          <TranslationProvider
            locale={locale}
            resources={resources}
            namespaces={i18nNamespaces}
          >
            <Icons />
            <Header />
            <main>{children}</main>
            <Footer />
          </TranslationProvider>
          <div id="__next"></div>
        </body>
      </html>
    </StoreProvider>
  );
}
