import type { Metadata } from "next";
import { ErrorBoundary } from "react-error-boundary";
import dynamic from "next/dynamic";
import { Icons } from "@/components/Icons";
import i18nConfig from "@/app/i18nConfig";
import initTranslations from "@/app/i18n";
import TranslationProvider from "@/app/[locale]/TranslationProvider";
import { StoreProvider } from "@/store/StoreProvider";
import ErrorFallback from "@/context/ErrorFallback";

const Header = dynamic(() => import("@/components/Header/Header"), {
  ssr: false,
});

const Footer = dynamic(() => import("@/components/Footer/Footer"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Lasertag",
  description: "Generated by create next app",
};

const i18nNamespaces = ["translation"];

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <StoreProvider>
      <TranslationProvider
        locale={locale}
        resources={resources}
        namespaces={i18nNamespaces}
      >
        <Icons />
        <Header locale={locale} />
        <ErrorBoundary FallbackComponent={ErrorFallback}>
          <main>{children}</main>
        </ErrorBoundary>
        <Footer />
      </TranslationProvider>
      <div id="__next"></div>
    </StoreProvider>
  );
}
